name: Daily Email API

on:
  schedule:
    - cron: '0 9 * * *'
  workflow_dispatch:

jobs:
  send_email:
    runs-on: ubuntu-latest
    
    steps:
    - name: Call API
      run: |
        curl --request GET \
        --url https://localhost:3000/api/email/sendEmailActual \
        --header 'authorization: Bearer ${{ secrets.GITHUB_TOKEN }}'
