name: Daily Email API

on:
  push:
    branches:
      - "dev"
  schedule:
    - cron: "0 9 * * *"
  workflow_dispatch:

jobs:
  send_email:
    runs-on: ubuntu-latest

    steps:
      - name: Call API
        run: |
          curl --request GET \
          --url http://localhost:3000/api/email/sendEmailActual \
